# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮件地址')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=32, verbose_name='性别')),
                ('city', models.CharField(max_length=64, verbose_name='城市')),
                ('sign', models.CharField(max_length=128, verbose_name='签名')),
                ('experience', models.BigIntegerField(max_length=128, verbose_name='积分')),
                ('ip', models.CharField(max_length=128, verbose_name='IP')),
                ('logins', models.BigIntegerField(max_length=128, verbose_name='登录次数')),
                ('joinTime', models.DateField(verbose_name='加入时间')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
            },
        ),
    ]
