# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='experience',
            field=models.BigIntegerField(verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='hostlist',
            name='logins',
            field=models.BigIntegerField(verbose_name='登录次数'),
        ),
    ]
