# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-19 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0002_auto_20181105_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮件地址'),
        ),
        migrations.AlterField(
            model_name='hostlist',
            name='experience',
            field=models.IntegerField(verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='hostlist',
            name='logins',
            field=models.IntegerField(verbose_name='登录次数'),
        ),
    ]
