# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(verbose_name='手机号码'),
        ),
    ]
