# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-19 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20181030_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
